import { sendMail } from "@/lib/email/smtp";

type PasswordResetEmailInput = {
  to: string;
  resetUrl: string;
};

export function buildPasswordResetEmail({ resetUrl }: PasswordResetEmailInput) {
  const subject = "Reset your FX Admin password";
  const text = [
    "FX Admin password reset",
    "",
    "Use the link below to set a new password:",
    resetUrl,
    "",
    "If you did not request this reset, you can ignore this email.",
  ].join("\n");

  const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>${subject}</title>
  </head>
  <body style="margin:0;background:#c7f8fe;color:#001619;font-family:Inter,Arial,sans-serif;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#c7f8fe;padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:560px;background:#ecfcff;border:1px solid rgba(0,22,25,.14);border-radius:16px;box-shadow:0 10px 15px -3px rgba(0,22,25,.08);overflow:hidden;">
            <tr>
              <td style="background:#001619;padding:24px 28px;color:#c7f8fe;">
                <div style="font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#50e8f4;">Cignum Solutions</div>
                <div style="margin-top:8px;font-size:24px;line-height:32px;font-weight:800;color:#c7f8fe;">FX Admin password reset</div>
              </td>
            </tr>
            <tr>
              <td style="padding:28px;">
                <p style="margin:0 0 16px;font-size:16px;line-height:24px;color:#071f22;">A password reset was requested for your FX Admin account.</p>
                <p style="margin:0 0 24px;font-size:14px;line-height:22px;color:#3c494a;">Use the secure button below to set a new password. The link is generated by Supabase Auth and should only be used by you.</p>
                <a href="${resetUrl}" style="display:inline-block;background:#50e8f4;color:#001619;text-decoration:none;font-weight:800;border-radius:8px;padding:12px 18px;border:1px solid rgba(0,22,25,.18);">Reset password</a>
                <p style="margin:24px 0 0;font-size:13px;line-height:20px;color:#3c494a;">If the button does not work, copy and paste this link into your browser:</p>
                <p style="margin:8px 0 0;font-size:12px;line-height:18px;color:#071f22;word-break:break-all;">${resetUrl}</p>
              </td>
            </tr>
            <tr>
              <td style="padding:18px 28px;background:#dff8fc;border-top:1px solid rgba(0,22,25,.1);font-size:12px;line-height:18px;color:#3c494a;">Ignore this email if you did not request a password reset.</td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;

  return { subject, text, html };
}

export async function sendPasswordResetEmail(input: PasswordResetEmailInput) {
  const email = buildPasswordResetEmail(input);
  await sendMail({
    to: input.to,
    ...email,
  });
}
